### ISSUE TITLE
Can I set negative_prompt and scheduler in this version or later?

### ISSUE THREAD

**Issue by SunchaoLive** [StefH/Replicate.Net#11]

**Comment by StefH** [comment]
The default create prediction does not have negative_prompt and scheduler
https://replicate.com/docs/reference/http#predictions.create

However. you can also create your own model, and serialize this to json and call the
- `Task<Prediction> CreatePredictionAsync([Body] string request, CancellationToken cancellationToken = default);` method

**Comment by SunchaoLive** [comment]
Thanks for the reply, will have a try 👍
