### ISSUE TITLE
Provide a downloadable .dll ?

### ISSUE THREAD

**Issue by hughperkins** [StefH/Replicate.Net#5]
Hi, Cool :) Provide a downloadable .dll, e.g. attached to the latest release? That wiill make hte library easier to use :)

**Comment by hughperkins** [comment]
Oh, it's on nuget, cool. Maybe make it really clear that one can install by clicking on the nuget link or similar?

(eg for Unity people, we basically download the nuget package, then rename to have `.zip` suffix, then unzip, then drag the dll into our Unity project; we dont use nuget itself; at least, I dont)

**Comment by StefH** [comment]
0.0.3 is added to releases.

https://github.com/StefH/Replicate.Net/releases/tag/0.0.3

**Comment by hughperkins** [comment]
Thanks!
